
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // CLI (db push, migrate, studio) needs a direct Postgres connection.
    // With Prisma Dev, use the TCP URL on port 51214 — not prisma+postgres:// on 51213.
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
